### ISSUE TITLE
Module review

### ISSUE THREAD

**Issue by agentrickard** [patrickfweston/workbench_reviewer#1]
Here we go, in no particular order.

Note: I love the integration to Workbench proper :-) including matching icon.

Forms
=====

* I'm not sure I like moving the Revision Log to the Workflow tab. It might be better to put the Reviewer field in the revisions tab, since that tab is open by default when revisions are turned on. As it stands, I have to hunt for both the Reviewer and Log fields. _Copied to #8._

* `workbench_reviewer_form_node_form_alter()` does not check to see if Workbench Reviewer / Moderation was enable for the bundle type, contradicting what's in `workbench_reviewer_entity_bundle_field_info()`. 

* Would be nice to have the reviewer element added to the Workbench Moderation quick form `EntityModerationForm`. _Copied to #6._

Interoperability
======

* This should also work with Content Moderation. It should, because the base field `moderation_state` is also defined there. Would be nice to have a test for that. _Copied to #5 ._

* The module defines `workbench_moderation` as a dependency, which isn't quite true. The dependency check can be moved to [hook_requirements()](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Extension%21module.api.php/function/hook_requirements/8.4.x) and set to check on install. _Copied to #5._

Code Style
======

* Since we declare `use Drupal\Core\Field\BaseFieldDefinition;` we don't need to full autoloader path when used in code later. 

Before:
```$definitions['workbench_reviewer'] = \Drupal\Core\Field\BaseFieldDefinition::create('entity_reference')```

After:
```$definitions['workbench_reviewer'] = BaseFieldDefinition::create('entity_reference')``` 

(See Content Moderation / Workbench Moderation's `EntityTypeInfo::entityBaseFieldInfo()` for reference.)

_Copied to #4 ._

Permissions
======

General permissions issue: _Copied to #3 ._

* I think the module needs it's own permission set. Primarily "Assign Workbench Reviewer"  and "Be Assigned Workbench Reviewer". That would be more in line with how the rest of the suite works.

* "Assign" would control who can see and use the field / form element. Use [hook_entity_field_access()](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Entity%21entity.api.php/function/hook_entity_field_access/8.4.x).

* "Be assigned" would control who can be selected and who can use the Workbench tab.

Adding the "Be assigned" gives more control and creates some complexity. 

* The list of who can be assigned should be alterable by other modules after creation -- think Workbench Access integration.

* Filtering the entity_reference autocomplete by permission requires, I believe, the creation of a new Field Widget. See https://github.com/agentrickard/workbench_access/blob/8.x-1.x/src/Plugin/EntityReferenceSelection/UserFilteredSelection.php for an example.

Base Fields
=====

This one is more of a question. I have this issue in Domain Access as well. 

* If we use Base Fields, the Reviwer field cannot be removed or controlled via field settings. I don't know if this is a bad thing or not. What if I install it on a moderated content type and then decide I don't want it? This is less important since the field is optional.

Node logic / entity types
======

General extension to other entity types issue: _Copied to #2 ._

* Not urgent, but be aware that the plans for WBM and CM are to extend to other entity types. The current checks only look at nodes, which may be a false limitation. 

* Checking `$entity_type->id() == 'node'` might be removed.

* Using `workbench_reviewer_form_node_form_alter()` might also need to change. Not sure if there is a generic entity form alter.

Tests
=====

General testing issue: _Copied to #12_

* The module could use some tests. This is a great chance to work with the interns or to learn how to write Functional / Kernel tests. Some testing ideas:

* Ensure field is created for existing content types
* Ensure field is created when content type added to moderation
* Ensure field is removed when content type removed from moderation
* Ensure that Reviewer field data is stored properly on save.
* Ensure that Reviewer field data is removed properly on delete.
* Test field visibility if "assign" permission is added
* Test view visibility if "be assigned" permission is added

Tests would likely need to be written against Content Moderation, since that is available in core.

**Comment by patrickfweston** [comment]
Closing this issue since it has been broken into smaller issues.
